title: Data Engineering Notes
description: Data Engineering Notes
url: "https://hoile9119.github.io"
baseurl: "/de-notes"

theme: jekyll-theme-dinky

exclude:
  - CLAUDE.md
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
